### ISSUE TITLE
Template url support

### ISSUE THREAD

**Issue by larserikfinholt** [jwstadler/angular-jquery-dialog-service#3]
Support for template url would have been great!

Something like

dialogService.open("/Modules/Templates/issueDialogTemplate.html", model, options)
instead of
dialogService.open("myDialog", "issueDialogTemplate.html", model, options)

Thanks for a handy service

**Comment by jwstadler** [comment]
Hi larserikfinholt ,

I have added this capability to the service. Now, you can pass a URL instead of a template id and the service will retrieve the template fragment from the server. Hope that helps. Have a great day!

**Comment by larserikfinholt** [comment]
Thanks!
