### ISSUE TITLE
Seeking License Type Clarification

### ISSUE THREAD

**Issue by richdenis** [jwstadler/angular-jquery-dialog-service#4]
Hello,

I am writing to find out what type of license this module is licensed under.  I work for a software company that has strict policies on what licenses we can use in our product.  Can you please indicate what license you have this work under?  Our preference would be MIT.  

Thanks in advance,
Rich

**Comment by jwstadler** [comment]
Hi Rich,

No problem at all. I have added the MIT License file to the project so you should be good to go. Have a great day!
